# Generated by Django 3.0.4 on 2020-03-09 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('size', models.IntegerField()),
                ('price', models.FloatField()),
                ('rooms', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('added_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('AVAILABLE', 'available'), ('RENTED', 'rented')], default='AVAILABLE', max_length=10)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realtor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
