# Generated by Django 3.0.4 on 2020-03-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200315_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='address',
            field=models.CharField(default='Sudbury, Canada', max_length=300),
        ),
    ]
